version: 0.2

phases:
  install:
    commands:
      - npm i --force
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist $S3_BUCKET